[DFS, BFS] 10월 11일
Altu-Bitu-5/Altu-Bitu-ChoiEunbyeol pull request #6
Opened 2023-10-10 18:03 UTC by dmsquf03

### 인적사항
학번: 2271062
이름: 최은별
</br>

### 과제제출
기존 제출: 1325, 2615, 4963
추가 제출:
</br>

2023-10-13 12:49 UTC, mingulmangul requested changes
**[DFS/BFS 구현 코드 리뷰 완료]**
2615(P1)
안녕하세요 은별님!
이번 구현 문제가 살짝 난이도가 있다고 생각했는데 너무 잘 풀어주신 것 같습니다🥰
그리고 제가 풀어보지 못한 재귀 방식으로 문제를 풀어주셔서 코드 읽어보면서 저도 새로운 걸 얻어가네요 감사합니다 ㅎㅎ
바꿔보면 좋을 것 같다고 생각한 점들 코멘트로 남겼습니다. 한 번 읽어봐주세요!
과제하느라 고생하셨어요!!💚

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +                    }
P1. 여기서는 삼중 for문을 통해서 모든 칸(i, j)과 방향(mov)을 순차적으로 탐색하고 있네요. 그러면 이전에 방문한 노드를 다시 방문할 일이 없기 때문에 `visited` 변수나 이 변수를 이용해서 방문 체크하는 과정은 생략해도 될 것 같아요!

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +            if(map[j][i] != 0) {
P2. 이 if문에서 조건이 맞지 않을 때 바로 continue를 써서 다음으로 넘어가면 어떤가요?? 너무 깊게 인덴테이션이 들어가는건 지양하는게 좋아요! 여기도 아래 35번째 라인처럼 if-continue 구조로 나타내면, 삼중 for문으로 깊어진 인덴테이션을 한 단계 낮게 만들 수 있을 것 같습니다 :)

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +    }
P2. if문 안에서 return을 하면 어차피 그 다음 코드들은 실행되지 않아요! 즉, return된 이후에 else 문은 항상 실행되지 않기 때문에, else 없이 바로 `return 0`을 써도 됩니다! 그러면 코드의 양이 줄어서 읽기도 더 쉬워져요 👍

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +int dfs(int r, int c, int mov, int cnt) { // 재귀 dfs
재귀를 사용해서 푸셨네요 멋집니다!! 강의에서 보여드렸던 풀이는 재귀 대신 반복문을 사용했었는데, 여러 방식의 풀이를 비교해보고 가장 효율적인 걸 찾아보시는 것도 좋을 것 같아요 🤗🤗

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +}
범위 체크하는 함수를 따로 분리하셨네요! 덕분에 코드가 더 깔끔하고 가독성 있는 것 같아 좋습니다 👍

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +vector<vector<int>> moving = { {0,1}, {1,0}, {1,1}, {-1,1} };
P3. 이렇게 길거나 반복 사용되는 타입들은 `typedef`를 이용해서 새로운 타입으로 정의해두고 사용하는 것도 좋아요! 매번 치기 번거롭기도 하니까요 ㅎㅎ

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +    }
P2. 여기서도 if문 안에 return을 추가하면, 뒤에 else는 생략하고 바로 출력할 수 있겠죠??

2023-10-13 12:49 UTC, mingulmangul commented on 08_DFS_BFS/2615.cpp
> +#define MAX 19
`MAX`를 상수로 설정하고 사용하셨네요! 이렇게 여러 번 사용되는 숫자는 상수로 정의하고 사용하는게 실수의 가능성도 줄이고 유지보수 측면에도 좋아요 👍👍

2023-10-15 12:33 UTC, Goldchae approved these changes
[BFS&DFS 알고리즘 코드 리뷰 완료]
p3. 전체적으로 깔끔하고 좋은 코드로 작성해주셨네요! 코멘트 남긴 부분 확인해주세요! 수고하셨습니다!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/1325.cpp
> +    vector<bool> visited (n+1, false);
n+1로 초기화해주신 점 좋습니다!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/1325.cpp
> +
다음에는 주석도 달아주세요!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/1325.cpp
> +int bfs(int n, int v){
깔끔한 BFS 코드네요! 이 문제를 dfs로도 풀 수 있을까요? 가능하다면 한번 작성해보셔도 좋을 것 같아요!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/4963.cpp
> +int dy[] = { 0, 1, 0, -1, -1, 1, -1, 1 };
8방향 탐색용 배열 두 개 선언 스킬 사용해주신 점 좋습니다!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/4963.cpp
> +void dfs(int x, int y) { // 재귀 dfs
여기서는 재귀 DFS를 사용해 주셨네요! 두 방법 모두 사용해보는 방법으로 과제 제출해주신 점 좋습니다!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/4963.cpp
> +        cout << result << '\n';
\n보다는 endl이 시간복잡도 상 좋습니다!

2023-10-15 12:33 UTC, Goldchae commented on 08_DFS_BFS/4963.cpp
> +bool isInRange(int x, int y){
범위 체크 함수를 바깥으로 빼 주셨네요! 관련 변수명이 길거나 범위 관련 수식이 많은 경우에 더욱 유용하답니다

2023-10-18 08:09 UTC, dmsquf03 commented on 08_DFS_BFS/2615.cpp
> +                    }
이 부분을 삭제했더니 백준 제출 시에 13퍼센트에서 틀립니다ㅠㅠ
6개 이상 연속된 돌을 못 제외시키는 것 같습니다..

2023-10-18 08:13 UTC, dmsquf03 commented on 08_DFS_BFS/2615.cpp
> +            if(map[j][i] != 0) {
인덴테이션 때문에 고민이 많았는데 이런 간단한 방법으로 낮출 수 있었네요..ㅎㅎ
수정했습니다! 감사합니다

2023-10-18 08:14 UTC, dmsquf03 commented on 08_DFS_BFS/2615.cpp
> +    }
수정했습니다! 감사합니다!!

2023-11-07 22:06 UTC, merged